languageCode = "en"
languageName = "English"
weight = 1
title = "Doge HQ"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "20 November 2024"
  logo = "img/doge_logo_transparent.png"
  description = "Department of Government Efficiency"

[params.author]
  name = "Doge HQ"
  email = "dogehq.blog@gmail.com"
  image = "img/doge_logo.png"
  headline = "Department of Government Efficiency"
  bio = "Doge: Department of Government Efficiency"
  links = [
    { x-twitter = "https://www.goodreads.com/work/quotes/45485993-the-100-best-yo-mama-jokes" },
  ]