languageCode = "en"
languageName = "English"
weight = 1
title = "Doge HQ"

[params]
  displayName = "English"
  isoCode = "en"
  rtl = false
  dateFormat = "2 January 2006"
  logo = "img/doge_logo_transparent.png"
  description = "Department of Government Efficiency"

[params.author]
  name = "Doge HQ"
  email = "dogehq.blog@gmail.com"
  image = "img/doge_logo.png"
  headline = "Department of Government Efficiency"
  bio = "Department of Government Efficiency"
  links = [
    { x-twitter = "https://x.com/TheDogeHQBlog" },
  ]